# Generated by Django 4.1.5 on 2023-01-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_date_product_price_alter_product_image"),
        ("product", "0005_alter_product_date"),
    ]

    operations = []
