# Generated by Django 4.1.5 on 2023-01-26 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_date_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="undefind", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 26, 10, 41, 17, 147926, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
