# Generated by Django 4.1.5 on 2023-01-26 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_alter_product_category_alter_product_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(default="default_slug", max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 26, 11, 41, 2, 741371, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pruduct_code",
            field=models.CharField(default="underfind", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor_code",
            field=models.CharField(default="underfind", max_length=30, unique=True),
        ),
    ]
