# Generated by Django 4.1.5 on 2023-01-26 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0013_product_slug_alter_category_name_alter_product_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 26, 11, 42, 22, 50119, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
