# Generated by Django 4.1.5 on 2023-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_alter_product_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.CharField(max_length=100),
        ),
    ]
