# Generated by Django 4.1.5 on 2023-01-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_alter_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pruduct_code",
            new_name="code",
        ),
    ]
