# Generated by Django 4.1.5 on 2023-01-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(default="undefined", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor_code",
            field=models.CharField(default="undefined", max_length=30, unique=True),
        ),
    ]
