# Generated by Django 4.1.5 on 2023-01-28 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_product_from_csv_alter_product_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 28, 8, 25, 5, 720468, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
